name: Copilot Agent Workflow

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  copilot:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: github/copilot-preview/actions@v0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          copilotToken: ${{ secrets.COPILOT_TOKEN }}
          